name: Deploy to Dash Hosting

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v3

      - name: Копируем файлы на сервер (через SCP)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          source: "."
          target: "/home/container"
          strip_components: 1