name: Deploy via SCP

on:
  push:
    branches:
      - main  # или твоя ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Upload files via SCP
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}  # если аутентификация через пароль
        port: 22
        source: "./"            # или нужная папка
        target: "/home/container/cogs"  # папка на сервере