name: Deploy via SFTP

on:
  push:
    branches:
      - main  # или другая ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy files via SFTP
      uses: appleboy/sftp-action@master
      with:
        host: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: 22
        source: "./"            # тут укажи нужную папку или "./" для корня репо
        target: "/home/container/cogs"  # путь на сервере